import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, CheckCircle2, FileImage, Headphones, KeyRound, Link2, LoaderCircle, LogIn, MessageSquareWarning, QrCode, Save, Shield, ShieldCheck, Upload } from 'lucide-react';
import { checkMessageSafety, checkOtpSafety, checkPublicPaymentProof, checkQrSafety, fetchSafetyDashboard, loginSafetyUser, registerSafetyUser, runShieldSafetyScan, saveSafetyReport } from '../utils/api';
import { decodeQrImage } from '../utils/qrDecoder';

const shell = 'min-h-screen bg-[#F2F1F0] dark:bg-[#111] text-[#2b3033] dark:text-white px-4 py-8 sm:py-12 font-sans';
const card = 'rounded-xl border border-slate-300 dark:border-white/10 bg-white/70 dark:bg-[#1a1c1e] p-5 sm:p-6 shadow-sm';
const button = 'w-full rounded-lg bg-[#15BCDF] hover:bg-[#3fd0ef] px-5 py-3.5 text-xs font-bold uppercase tracking-wider text-[#111] disabled:opacity-50';
const input = 'w-full rounded-lg border border-slate-300 dark:border-white/10 bg-white dark:bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#15BCDF]';
const tools = [
  ['/user/qr-check', 'QR Safety Check', QrCode], ['/user/message-check', 'Scam Message Check', MessageSquareWarning],
  ['/user/otp-check', 'OTP Scam Check', KeyRound], ['/user/audio-check', 'Audio Scam Check', Headphones],
  ['/user/payment-proof', 'Payment Screenshot Verify', FileImage], ['/user/shield-scan', 'Shield Scan', Shield],
];

function useResultSaver(checkType, result) {
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const available = Boolean(localStorage.getItem('trustpay_token')) && Boolean(result);
  const save = async () => {
    setSaving(true);
    const rawRisk = result.riskLevel || result.risk || 'UNKNOWN';
    const riskLevel = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'NORMAL', 'SUSPICIOUS', 'UNKNOWN'].includes(rawRisk) ? rawRisk : 'UNKNOWN';
    const details = result.indicators || result.reasons || [];
    const response = await saveSafetyReport({ checkType, riskLevel, resultCode: result.resultCode || result.result || `${riskLevel}_RISK`, summary: details.slice(0, 4).join('; ') || `${checkType} check returned ${riskLevel}.` });
    setSaving(false); setSaved(Boolean(response.success));
  };
  return { saving, saved, save, available };
}

function Header({ title, subtitle }) {
  return <header className="mx-auto max-w-5xl"><Link to="/user" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-500 hover:text-[#15BCDF]"><ArrowLeft className="h-4 w-4"/>Safety Hub</Link><div className="mt-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#15BCDF] text-white"><ShieldCheck className="h-6 w-6"/></span><div><p className="text-xs font-black tracking-[.18em]">TRUSTPAY</p><h1 className="text-2xl sm:text-3xl font-black uppercase tracking-wider">{title}</h1></div></div>{subtitle && <p className="mt-3 max-w-2xl text-sm text-slate-500">{subtitle}</p>}</header>;
}

function Result({ result, onSave, saving, saved }) {
  if (!result) return null;
  const level = result.riskLevel || result.risk || result.result;
  const severe = ['HIGH', 'CRITICAL', 'SUSPICIOUS', 'INVALID_QR'].includes(level);
  return <section className={`${card} mt-6`} aria-live="polite"><div className={`flex items-center gap-2 font-black uppercase tracking-wider ${severe ? 'text-red-500' : level === 'LOW' || level === 'NORMAL' ? 'text-emerald-500' : 'text-amber-500'}`}>{severe ? <AlertTriangle className="h-5 w-5"/> : <CheckCircle2 className="h-5 w-5"/>}{level}</div>{result.type && <p className="mt-4 text-sm"><span className="text-slate-500">Type:</span> <strong>{result.type}</strong></p>}{result.registeredMerchant && <div className="mt-4 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="font-black text-emerald-500">TRUSTPAY REGISTERED MERCHANT ✓</p><p className="mt-2 text-sm">{result.registeredMerchant.businessName}</p><p className="text-sm text-slate-500">{result.registeredMerchant.merchantId}</p></div>}{result.payee && <p className="mt-3 text-sm">Payee: <strong>{result.payee}</strong></p>}{result.merchantName && <p className="mt-2 text-sm">Merchant: <strong>{result.merchantName}</strong></p>}{result.indicators?.length > 0 && <div className="mt-4"><p className="text-xs font-bold uppercase tracking-wider">Detected indicators</p><ul className="mt-2 list-disc pl-5 text-sm text-slate-600 dark:text-slate-300">{result.indicators.map(item => <li key={item}>{item}</li>)}</ul></div>}{result.reasons?.length > 0 && <ul className="mt-4 list-disc pl-5 text-sm text-slate-600 dark:text-slate-300">{result.reasons.map(item => <li key={item}>{item}</li>)}</ul>}{result.recommendation && <p className="mt-4 text-sm font-semibold">{result.recommendation}</p>}{onSave && <button onClick={onSave} disabled={saving || saved} className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#15BCDF]"><Save className="h-4 w-4"/>{saving ? 'Saving…' : saved ? 'Saved' : 'Save to my account'}</button>}</section>;
}

export function SafetyHub() {
  return <div className={shell}><main className="mx-auto max-w-5xl"><div className="text-center"><ShieldCheck className="mx-auto h-10 w-10 text-[#15BCDF]"/><p className="mt-3 text-xs font-black tracking-[.2em]">TRUSTPAY</p><h1 className="mt-2 text-3xl sm:text-4xl font-black uppercase tracking-wider">Safety Hub</h1><p className="mt-3 text-slate-500">Check something suspicious before you act.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tools.map(([to, label, Icon]) => <Link key={to} to={to} className={`${card} group min-h-36 flex flex-col justify-between hover:border-[#15BCDF] transition-colors`}><Icon className="h-7 w-7 text-[#15BCDF]"/><span className="mt-8 text-sm font-black uppercase tracking-wider">{label}</span></Link>)}</div><section className={`${card} mt-8 text-center`}><h2 className="font-black uppercase tracking-wider">Create free TrustPay account</h2><p className="mt-2 text-sm text-slate-500">Save safety reports · View check history · Link a Guardian · Receive important alerts</p><div className="mt-5 flex flex-col sm:flex-row justify-center gap-3"><Link to="/user/register" className="rounded-lg bg-[#15BCDF] px-5 py-3 text-xs font-bold uppercase tracking-wider text-[#111]">Create account</Link><Link to="/user/login" className="rounded-lg border border-slate-300 dark:border-white/10 px-5 py-3 text-xs font-bold uppercase tracking-wider">Sign in</Link></div></section></main></div>;
}

export function QrSafetyCheck() {
  const [payload, setPayload] = useState(''); const [decoded, setDecoded] = useState(''); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [decodeError, setDecodeError] = useState(false);
  const analyse = async value => { setLoading(true); setError(''); setResult(null); try { const response = await checkQrSafety(value ?? payload); if (!response.success) throw new Error(response.message); setResult(response.result); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const upload = async event => {
    const file = event.target.files?.[0];
    if (!file) return;
    setLoading(true); setError(''); setDecodeError(false); setDecoded(''); setPayload(''); setResult(null);
    try {
      const value = await decodeQrImage(file);
      if (!value) { setDecodeError(true); return; }
      setPayload(value); setDecoded(value);
      const response = await checkQrSafety(value);
      if (!response.success) throw new Error(response.message);
      setResult(response.result);
    } catch (err) { setError(err.message); }
    finally { setLoading(false); event.target.value = ''; }
  };
  return <div className={shell}><Header title="QR Safety Check" subtitle="Decode and inspect a QR destination before opening or paying."/><main className="mx-auto mt-8 max-w-2xl"><section className={card}><label className="text-xs font-bold uppercase tracking-wider">QR text or payment URL</label><textarea value={payload} onChange={e => { setPayload(e.target.value); setDecoded(''); setDecodeError(false); }} className={`${input} mt-2 min-h-28`} placeholder="upi://pay?... or https://..."/><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-slate-400 p-4 text-xs font-bold uppercase tracking-wider"><Upload className="h-4 w-4"/>Upload QR image<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={upload}/></label>{loading && <p className="mt-3 flex items-center gap-2 text-sm text-[#15BCDF]"><LoaderCircle className="h-4 w-4 animate-spin"/>Decoding and checking QR…</p>}{decoded && <div className="mt-4 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="font-black text-emerald-500">QR DETECTED ✓</p><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">Decoded Content</p><p className="mt-1 break-all text-sm font-mono">{decoded}</p></div>}{decodeError && <div role="alert" className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4"><p className="font-black text-amber-600">UNABLE TO READ QR</p><p className="mt-2 text-sm">No QR code was detected in this image.</p><p className="mt-3 text-xs font-bold uppercase tracking-wider">Try:</p><ul className="mt-1 list-disc pl-5 text-sm text-slate-600 dark:text-slate-300"><li>uploading a clearer image</li><li>cropping around the QR</li><li>avoiding blur or glare</li></ul></div>}{error && <p className="mt-3 text-sm text-red-500">{error}</p>}<button onClick={() => analyse()} disabled={loading || !payload.trim()} className={`${button} mt-4`}>{loading ? 'Checking…' : 'Check QR'}</button></section><QrAnalysisResult result={result}/></main></div>;
}

function QrAnalysisResult({ result }) {
  if (!result) return null;
  const level = result.risk || result.result;
  const suspicious = ['SUSPICIOUS', 'INVALID_QR'].includes(level);
  return <section className={`${card} mt-6`} aria-live="polite"><div className={`flex items-center gap-2 font-black uppercase tracking-wider ${suspicious ? 'text-red-500' : level === 'NORMAL' ? 'text-emerald-500' : 'text-amber-500'}`}>{suspicious ? <AlertTriangle className="h-5 w-5"/> : <CheckCircle2 className="h-5 w-5"/>}{level}</div><div className="mt-4 grid gap-3 text-sm"><p><span className="text-slate-500">QR Type:</span> <strong>{result.type || 'UNKNOWN'}</strong></p>{result.payee && <p><span className="text-slate-500">Recipient:</span> <strong>{result.payee}</strong></p>}{result.registeredMerchant ? <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="font-black text-emerald-500">TRUSTPAY REGISTERED MERCHANT ✓</p><p className="mt-3"><span className="text-slate-500">Merchant:</span> <strong>{result.registeredMerchant.merchantName || result.registeredMerchant.businessName}</strong></p><p className="mt-2"><span className="text-slate-500">Merchant ID:</span> <strong>{result.registeredMerchant.merchantId}</strong></p><p className="mt-2"><span className="text-slate-500">Destination:</span> <strong>TrustPay Payment Page</strong></p><p className="mt-2"><span className="text-slate-500">Risk:</span> <strong>VERIFIED TRUSTPAY DESTINATION</strong></p></div> : result.type === 'UPI PAYMENT' && level === 'UNKNOWN' ? <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4"><p><span className="text-slate-500">TrustPay Status:</span> <strong>NOT REGISTERED / UNKNOWN</strong></p><p className="mt-2"><span className="text-slate-500">Risk:</span> <strong>UNKNOWN</strong></p><p className="mt-3">TrustPay could not independently verify this payment recipient. Confirm the recipient before paying.</p></div> : null}</div>{result.reasons?.length > 0 && <ul className="mt-4 list-disc pl-5 text-sm text-slate-600 dark:text-slate-300">{result.reasons.map(item => <li key={item}>{item}</li>)}</ul>}</section>;
}

export function TextSafetyCheck({ otp = false }) {
  const [message, setMessage] = useState(''); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const check = async () => { setLoading(true); setError(''); try { const response = await (otp ? checkOtpSafety(message) : checkMessageSafety(message)); if (!response.success) throw new Error(response.message); setResult(response.result); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <div className={shell}><Header title={otp ? 'OTP Scam Check' : 'Scam Message Check'} subtitle={otp ? 'Paste the message around the OTP. Do not paste or share your actual OTP.' : 'Paste suspicious SMS, WhatsApp, email or chat text for an explainable rule-based check.'}/><main className="mx-auto mt-8 max-w-2xl"><section className={card}>{otp && <p className="mb-4 rounded-lg bg-red-500/10 p-3 text-sm font-bold text-red-500">Never enter your actual OTP. Common numeric codes are redacted before analysis.</p>}<textarea value={message} onChange={e => setMessage(e.target.value)} className={`${input} min-h-44`} maxLength={10000} placeholder="Paste the suspicious message…"/>{error && <p className="mt-3 text-sm text-red-500">{error}</p>}<button onClick={check} disabled={loading || !message.trim()} className={`${button} mt-4`}>{loading ? 'Analysing…' : 'Analyse Message'}</button></section><Result result={result}/></main></div>;
}

export function PaymentProofCheck() {
  const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const upload = event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return setError('Image must be 5 MB or smaller.'); const reader = new FileReader(); reader.onload = async () => { setLoading(true); setError(''); try { const response = await checkPublicPaymentProof(reader.result); if (!response.success) throw new Error(response.message); setResult({ risk: response.result === 'VERIFIED_PAYMENT' ? 'NORMAL' : 'UNKNOWN', result: response.result, reasons: [response.result.replaceAll('_', ' ')] }); } catch (e) { setError(e.message); } finally { setLoading(false); } }; reader.readAsDataURL(file); };
  return <div className={shell}><Header title="Payment Screenshot Verify" subtitle="Uses TrustPay’s existing payment-proof OCR and trusted transaction matching. Private merchant transaction data is not exposed."/><main className="mx-auto mt-8 max-w-2xl"><section className={card}><label className="flex cursor-pointer flex-col items-center gap-3 rounded-lg border border-dashed border-slate-400 p-10 text-center"><FileImage className="h-9 w-9 text-[#15BCDF]"/><strong>Upload payment screenshot</strong><span className="text-xs text-slate-500">PNG, JPEG or WebP · maximum 5 MB</span><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label>{loading && <p className="mt-4 flex items-center gap-2 text-sm"><LoaderCircle className="h-4 w-4 animate-spin"/>Analysing real payment evidence…</p>}{error && <p className="mt-3 text-sm text-red-500">{error}</p>}</section><Result result={result}/></main></div>;
}

export function AudioSafetyCheck() { return <div className={shell}><Header title="Audio Scam Check" subtitle="The upload workflow is prepared for a future speech-to-text service."/><main className="mx-auto mt-8 max-w-2xl"><section className={card}><label className="flex items-center justify-center gap-2 rounded-lg border border-dashed border-slate-400 p-10 text-sm font-bold"><Headphones className="h-6 w-6 text-[#15BCDF]"/>Upload call recording<input type="file" accept="audio/*" className="sr-only" disabled/></label><button disabled className={`${button} mt-4`}>Analyse Audio</button><p className="mt-4 text-sm text-amber-600">Audio analysis is not active because no reliable speech-to-text service is configured. TrustPay will not generate a fake result.</p></section></main></div>; }

export function ShieldScan() {
  const [message, setMessage] = useState(''); const [qr, setQr] = useState(''); const [proof, setProof] = useState(null); const [report, setReport] = useState(null); const [loading, setLoading] = useState(false);
  const selectProof = event => { const file = event.target.files?.[0]; if (!file || file.size > 5 * 1024 * 1024) return; const reader = new FileReader(); reader.onload = () => setProof(reader.result); reader.readAsDataURL(file); };
  const scan = async () => { setLoading(true); const response = await runShieldSafetyScan(message.trim(), qr.trim(), proof); setLoading(false); if (response.success) setReport({ risk: response.result.riskLevel, result: response.result.resultCode, reasons: response.result.reasons }); else setReport({ risk: 'UNKNOWN', result: 'SHIELD_ERROR', reasons: [response.message] }); };
  return <div className={shell}><Header title="TrustPay Shield Scan" subtitle="Combines only the real signals you provide. No fraud probability is invented."/><main className="mx-auto mt-8 max-w-2xl"><section className={`${card} space-y-4`}><textarea className={`${input} min-h-28`} value={message} onChange={e => setMessage(e.target.value)} placeholder="Suspicious message (optional)"/><textarea className={`${input} min-h-24`} value={qr} onChange={e => setQr(e.target.value)} placeholder="Decoded QR text or URL (optional)"/><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-slate-400 p-4 text-xs font-bold uppercase tracking-wider"><FileImage className="h-4 w-4"/>{proof ? 'Payment screenshot selected' : 'Add payment screenshot (optional)'}<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={selectProof}/></label><button className={button} disabled={loading || (!message.trim() && !qr.trim() && !proof)} onClick={scan}>{loading ? 'Building report…' : 'Run Shield Scan'}</button></section><Result result={report}/></main></div>;
}

export function SafetyAccount({ login = false, setUser }) {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async e => { e.preventDefault(); setLoading(true); setError(''); const response = login ? await loginSafetyUser(form.email, form.password) : await registerSafetyUser(form.name, form.email, form.password); setLoading(false); if (!response.success) return setError(response.message); localStorage.setItem('trustpay_user', JSON.stringify(response.user)); sessionStorage.setItem('trustpay_account_notice', response.message || 'Signed in successfully.'); setUser?.(response.user); navigate('/user/dashboard'); };
  return <div className={shell}><Header title={login ? 'User Login' : 'Create Safety Account'} subtitle="Basic safety tools remain available without an account."/><main className="mx-auto mt-8 max-w-md"><form onSubmit={submit} className={`${card} space-y-4`}>{!login && <input className={input} placeholder="Name" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/>}<input className={input} type="email" placeholder="Email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><input className={input} type="password" minLength={8} maxLength={128} placeholder="Password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>{error && <p className="text-sm text-red-500">{error}</p>}<button disabled={loading} className={button}>{loading ? 'Please wait…' : login ? 'Sign in' : 'Create account'}</button><Link className="block text-center text-xs font-bold text-[#15BCDF]" to={login ? '/user/register' : '/user/login'}>{login ? 'Create a free account' : 'Already have an account?'}</Link></form></main></div>;
}

export function SafetyDashboard() {
  const navigate = useNavigate(); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [notice] = useState(() => sessionStorage.getItem('trustpay_account_notice'));
  useEffect(() => { fetchSafetyDashboard().then(r => { if (!r.success) navigate('/user/login', { replace: true }); else setData(r); }).finally(() => setLoading(false)); }, [navigate]);
  if (loading) return <div className={`${shell} grid place-items-center`}><LoaderCircle className="h-7 w-7 animate-spin text-[#15BCDF]"/></div>;
  if (!data) return null;
  return <div className={shell}><Header title="User Dashboard" subtitle={`Welcome, ${data.user.name}.`}/><main className="mx-auto mt-8 max-w-5xl">{notice && <p className="mb-4 rounded-lg border border-[#15BCDF]/30 bg-[#15BCDF]/10 p-3 text-sm">{notice}</p>}{data.pendingGuardianRequests > 0 && <Link to="/user/guardian" className="mb-4 flex items-center justify-between rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm font-bold text-amber-500"><span>{data.pendingGuardianRequests} Guardian protection request{data.pendingGuardianRequests === 1 ? '' : 's'} awaiting your decision.</span><span className="text-xs uppercase tracking-wider">Review</span></Link>}<div className="grid gap-4 md:grid-cols-2"><section className={card}><h2 className="font-black uppercase tracking-wider">Saved Safety Reports</h2>{data.reports.length ? <ul className="mt-4 space-y-3">{data.reports.map(r => <li key={r._id} className="rounded-lg border border-slate-200 dark:border-white/5 p-3"><strong>{r.checkType} · {r.riskLevel}</strong><p className="text-sm text-slate-500 mt-1">{r.summary}</p></li>)}</ul> : <p className="mt-4 text-sm text-slate-500">No safety checks saved yet.</p>}</section><section className={card}><h2 className="font-black uppercase tracking-wider">Recent Checks</h2><p className="mt-4 text-sm text-slate-500">{data.reports.length ? `${data.reports.length} saved check${data.reports.length === 1 ? '' : 's'} available in your report history.` : 'No safety checks saved yet.'}</p></section><section className={card}><h2 className="font-black uppercase tracking-wider">Guardian Protection</h2><p className={`mt-4 text-sm font-bold ${data.guardianStatus === 'ACTIVE' ? 'text-emerald-500' : 'text-slate-500'}`}>{data.guardianStatus === 'ACTIVE' ? `ACTIVE ✓ · ${data.guardian?.email}` : data.pendingGuardianRequests ? 'REQUEST AWAITING YOUR APPROVAL' : 'NOT LINKED'}</p><Link to="/user/guardian" className="mt-4 inline-block text-xs font-bold uppercase tracking-wider text-[#15BCDF]">{data.pendingGuardianRequests ? 'Review Guardian Requests' : 'Guardian Requests'}</Link></section><section className={card}><h2 className="font-black uppercase tracking-wider">Account Security</h2><p className="mt-4 text-sm text-slate-500">Your password is stored as a salted PBKDF2 hash. Never share passwords or OTPs.</p></section></div></main></div>;
}
